### ISSUE TITLE
Spikes in Network Analyzer

### ISSUE THREAD

**Issue by drJaser** [analogdevicesinc/m2k-fw#15] opened 2024-02-26 08:30 UTC
After upgrading FW on ADML2000 to v0.32 , Network Analyzer always shows some sort of sporadic spikes in response.
The circuit is low pass RC filter, so nothing complicated..
![image](https://github.com/analogdevicesinc/m2k-fw/assets/161296954/6ca20d51-eca6-4630-a226-52a9a099d8c4)

I took another ADML2000 with the same FW (already upgraded to v0.32) from my colegue in the office and the result was simillar.

After checking the same setup with brand new one ADML (original FW version 0.25), result was OK
![image](https://github.com/analogdevicesinc/m2k-fw/assets/161296954/8f648a57-d817-485d-af7f-03a37dca0cab)

My question is how to proper downgrade our (already upgraded) ADMLs back to original 0.25 firmware?
Where I can get files and guidelines to do that ?

Thanks,
Borut

**Comment by AlexandraTrifan** [comment] 2024-02-26 08:38
Hi,

You can find documentation on ADALM2000 firmware updating procedure here: https://wiki.analog.com/university/tools/m2k/common/firmware .

And you can download the firmware version you need from the releases page of this repository: https://github.com/analogdevicesinc/m2k-fw/releases .

I would recommend trying the v0.31 in order to see if this issue still happens since v0.25 is a pretty old firmware and multiple improvements were introduced in the last years.

Regarding the issue reported above, we will try to reproduce it and see what's causing it.

Thank you!
-Alexandra

**Comment by drJaser** [comment] 2024-02-26 19:21
Follow up report....
I downgraded back to 0.31 .. 
![image](https://github.com/analogdevicesinc/m2k-fw/assets/161296954/d1e854a0-64ac-47db-8fb5-a22ebf0cbb57)

and everything was as expected..
![image](https://github.com/analogdevicesinc/m2k-fw/assets/161296954/85105fac-10d7-4010-9f89-8035adfdd514)

then I tried to upgrade to v0.32 again..
![image](https://github.com/analogdevicesinc/m2k-fw/assets/161296954/05692b09-69cc-4206-8328-f386e00a4129)

and same story again.. obviously something wrong with latest release..
![image](https://github.com/analogdevicesinc/m2k-fw/assets/161296954/bc776ff8-f6f4-4136-ae93-e6c29f8da635)

BR

**Comment by adisuciu** [comment] 2024-02-27 11:12
We're looking into it

**Comment by drJaser** [comment] 2024-04-05 10:05
Any sollution for this bug ?

**Comment by drJaser** [comment] 2024-07-01 08:29
still nothing ??

**Comment by adisuciu** [comment] 2024-07-01 09:19
Just use 0.31 for now. We're working on a new firmware release ..

**Comment by mhennerich** [comment] 2024-10-11 14:14
Should be fixed in: https://github.com/analogdevicesinc/m2k-fw/releases/tag/v0.33

**Comment by mhennerich** [comment] 2024-10-11 14:15
Please reopen in case it's not.

**Closed as completed by mhennerich** 2024-10-11 14:15 UTC
